version: '3.8'

services:
  server:
    image: chaudhary64/url-shortner-api:latest
    container_name: url_shortner_server
    restart: always
    env_file:
      - .env
    networks:
      - web_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.url_shortner.rule=Host(`raiden-url.duckdns.org`)"
      - "traefik.http.routers.url_shortner.entrypoints=websecure"
      - "traefik.http.routers.url_shortner.tls.certresolver=myresolver"
      - "traefik.http.services.url_shortner.loadbalancer.server.port=3000"

networks:
  web_proxy:
    external: true
